# Generated by Django 5.2.10 on 2026-02-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='section_order',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
