# Generated by Django 5.2.10 on 2026-02-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_education_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='section_order',
            field=models.TextField(blank=True, default='header,skills,experience,education,summary'),
        ),
    ]
